# Ledge default configuration.

LEDGE_ADMIN_USER="jjj"
LEDGE_DEVELOPMENT_DIR="Development"
LEDGE_REPOSITORY_NAME="ledge"

LEDGE_WIREGUARD_INTERFACE="wg0"
LEDGE_WIREGUARD_PORT="51820"
LEDGE_WIREGUARD_NETWORK="10.44.0.0/24"
LEDGE_WIREGUARD_ADDRESS="10.44.0.1/24"

LEDGE_ENABLE_IPV6="false"
